apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: njocp-config
spec:
  destination:
    name: local-cluster
  project: njocp
  source:
    path: clusterconfig/aggregates/njocp-cluster-config
    repoURL: https://e7rock6fit01.datalinklabs.local/jamie.thibodeau/ambest2
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
