kind: Secret
apiVersion: v1
metadata:
  name: ldap-sync
  namespace: ldap-sync
stringData:
  ldap-sync.yaml: |
    kind: LDAPSyncConfig
    apiVersion: v1
    url: ldap://<Domain Name>
    bindDN: <LDAP Bind DN>
    bindPassword: <Bind Password>
    insecure: true
    augmentedActiveDirectory:
        groupsQuery:
            derefAliases: never
            pageSize: 0
        groupUIDAttribute: dn
        groupNameAttributes: [ cn ]
        usersQuery:
            baseDN: "<base search DN>"
            scope: sub
            derefAliases: never
            filter: (objectclass=person)
            pageSize: 0
        userNameAttributes: [ sAMAccountName ]
        groupMembershipAttributes: [ "memberOf:1.2.840.113556.1.4.1941:" ]
  whitelist.txt: |
    <DNs of Group>
    

type: Opaque


