apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- etcd-encryption.yaml
- openshift-gitops.yaml
- placement-all.yaml
- placement-ocp.yaml
- placement-hub.yaml
