
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: e7ocpcluster1-2vzcc
  name: e7ocpcluster1-2vzcc-infra
  namespace: openshift-machine-api

spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: e7ocpcluster1-2vzcc
      machine.openshift.io/cluster-api-machineset: e7ocpcluster1-2vzcc-infra
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: e7ocpcluster1-2vzcc
        machine.openshift.io/cluster-api-machine-role: infrastructure
        machine.openshift.io/cluster-api-machine-type: infrastructure
        machine.openshift.io/cluster-api-machineset: e7ocpcluster1-2vzcc-infra
    spec:
      metadata:
        creationTimestamp: null
        labels:
          node-role.kubernetes.io/infra: ""
      taints:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
      providerSpec:
        value:
          numCoresPerSocket: 2
          diskGiB: 120
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: 32768
          credentialsSecret:
            name: vsphere-cloud-credentials
          network:
            devices:
              - networkName: 
          metadata:
            creationTimestamp: null
          numCPUs: 8
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: 
            datastore: 
            folder: 
            resourcePool: 
            server: 
          template: e7ocpcluster1-2vzcc-rhcos
          apiVersion: machine.openshift.io/v1beta1
