apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: cluster-monitoring-config
data:
  config.yaml: |+
    # Enable monitoring your own services
    techPreviewUserWorkload:
      enabled: true
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      volumeClaimTemplate:
        metadata:
          name: alertmanager
        spec:
          resources:
            requests:
              storage: 40Gi
    prometheusK8s:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      volumeClaimTemplate:
        metadata:
          name: prometheus
        spec:
          resources:
            requests:
              storage: 40Gi
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    grafana:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
