apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paocp-cluster-config
spec:
  destination:
    name: paocp
  project: paocp
  source:
    path: clusterconfig/aggregates/pa-cluster-config
    repoURL: 
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
