apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paocp-cluster-config
spec:
  destination:
    name: paocp
  project: paocp
  source:
    path: clusterconfig/aggregates/paocp-cluster-config
    repoURL: https://e7rock6fit01.datalinklabs.local/jamie.thibodeau/ambest2
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
